<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    	<title>IT 207</title>
       	<link rel="stylesheet" href="stylesheet.css" type="text/css"/>
    </head>
    <body>
        <?php
        	include 'header.php';
        ?>
        <?php
        	include 'sidenav.php';
        ?>
        <?php
        	include 'footer.php';
        ?>
        <?php
        	include 'maincontent.php';
        ?>
    </body>
</html>